//
// Created by adrja on 22.03.2018.
//

#ifndef JIMP_EXERCISES_MINIMALTIMEDIFFERENCE_H
#define JIMP_EXERCISES_MINIMALTIMEDIFFERENCE_H


class MinimalTimeDifference {

};


#endif //JIMP_EXERCISES_MINIMALTIMEDIFFERENCE_H
